version: "3.9"

services:

  mongodb:
    image: mongo:6.0
    container_name: dashboard-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dashboard

  backend:
    image: dashboard-backend:latest
    container_name: dashboard-backend
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/dashboard
    networks:
      - dashboard-net

  frontend:
    image: dashboard-frontend:latest
    container_name: dashboard-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge